### ISSUE TITLE
Vendor pantsbuild/jarjar sources, and bump its asm dependency

### ISSUE THREAD

**Issue by alexarchambault** [eed3si9n/jarjar-abrams#11]
[pantsbuild/jarjar](https://github.com/pantsbuild/jarjar) is not maintained anymore (it's now marked as archived in particular). It'd be nice to copy its sources in this repository, so that they can be maintained from here. That should allow to bump its asm dependency in particular, which will probably be required for newer JDKs.

**Comment by eed3si9n** [comment]
- https://github.com/eed3si9n/jarjar-abrams/pull/15
- https://github.com/eed3si9n/jarjar-abrams/pull/20
