### ISSUE TITLE
Support for multiple libraries for the jarjarLibraryDependency setting?

### ISSUE THREAD

**Issue by BardurArantsson** [eed3si9n/jarjar-abrams#2]
Would it be possible to add support support for multiple libraries for the jarjarLibraryDependency setting? I have a use case where I need to shade multiple circe modules, and I'd really like to just specify all of them in a single go.

**Comment by eed3si9n** [comment]
I'll bring jarjar-abrams back to sbt-assembly where it originally started, and it can handle the multiple cases.

**Comment by BardurArantsson** [comment]
I've never been able to get sbt-assembly to work satisfactorily for me, FWIW. (I can't recall the issues, but IIRC we spent about two weeks trying to get it to work, but couldn't manage to get it working.)

**Comment by BardurArantsson** [comment]
Hm, turns out I have the same issues getting jarjar-abrams as sbt-assembly. It seems to require actually changing imports to use the shaded namespace[0], but my IDEA doesn't seem to be able to pick up on the fact that those imports should exist.

Oh well. I suppose we'll probably have to fork the coursier implementation and use that instead.

[0] ... which I find rather cumbersome,  strange, the way coursier does shading does not require this -- it post-processes the dependent code to rewrite references to the shaded libs automatically. Of course that has some build performance implications, but it is what it is.
